name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run package

      - name: Package VSIX
        run: |
          npx @vscode/vsce package
          echo "VSIX_PATH=$(ls *.vsix)" >> $GITHUB_ENV

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Extract changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}
          awk "/^## \[$VERSION\]/,/^## \[/" CHANGELOG.md | sed '$d' > release-notes.md
          [ -s release-notes.md ] || echo "Release v$VERSION" > release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.version.outputs.version }}
          body_path: release-notes.md
          files: ${{ env.VSIX_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Marketplace
        run: npx @vscode/vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
